{% set name = "seasocks" %}
{% set version = "1.4.6" %}

package:
  name: "{{ name|lower }}"
  version: "{{ version }}"

source:
  url: https://github.com/mattgodbolt/seasocks/archive/v{{ version }}.tar.gz
  sha256: fc69636ce1205d338d4c02784333b04cd774fa368843fcf9f4fe6f8530a2cd67

build:
  number: 0
  skip: true  # [osx]
  skip: true  # [win]

  run_exports:
    - {{ pin_subpackage('seasocks', max_pin='x.x.x') }}

requirements:
  build:
    - cmake
    - {{ compiler('cxx') }}
    - ninja
    - python

  host:
    - zlib

test:
  requires:
    - cmake
    - {{ compiler('cxx') }}
    - ninja
  files:
    - test

  commands:
    - test -f $PREFIX/lib/libseasocks.so
    - test -f $PREFIX/include/seasocks/Server.h
    - test -f $PREFIX/lib/cmake/Seasocks/SeasocksTargets.cmake
    - cd test
    - cmake . -GNinja -DCMAKE_BUILD_TYPE=Release
    - cmake --build . --config Release
    - ./program

about:
  home: https://github.com/mattgodbolt/seasocks
  license: BSD-2-Clause
  license_file: LICENSE
  summary: Simple, small, C++ embeddable webserver with WebSockets support

extra:
  recipe-maintainers:
    - apmorton
